# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Jekyll Blog
email: mishory@gmail.com
description: "an exercise i did for codeacademy afforded me a new static blog, this Jekyll based website, how about that!"
baseurl: "http://inbalmishory.net" # the subpath of your site, e.g. /blog
url: "http://inbalmishory.net" # the base hostname & protocol for your site
twitter_username: inbalmishory
github_username:  inbal-mishory

# Build settings
markdown: kramdown
encoding: utf-8
